name: "Lint"

on:
  push:
    paths-ignore:
      - "**/README.md"
      - "**/info.md"
      - "**/CHANGELOG.md"
      - "**/CONTRIBUTING.md"
      - "**/requirements.txt"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install ruff
        run: python3 -m pip install ruff==0.15.19

      - name: Lint
        run: python3 -m ruff check .

      - name: Format
        run: python3 -m ruff format . --check
